name: PHP CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup project
        run: make setup 
        
      - name: Run linter
        run: make lint
