name: PHP CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup project
        run: make setup 
          
      - name: Create table
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate
        
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test
        
    # - name: Run linter
    #   run: make lint
